### ISSUE TITLE
Perfect Pixel

### ISSUE THREAD

**Issue by Sha1fei** [Sergio-Ka/FlatUI#1]
Можешь пожалуйста выложить в инверсии макет и  настройки perfect pixel, по которым верстался макет.

**Comment by Sergio-Ka** [comment]
Создана ветка 1-fix-perfect-pixel, в корень положены макеты FlatUI.jpg и FlatUI-inverse.jpg (с инверсией, хотя использовался первый макет, а инверсия включалась в настройках PP) и файл настроек perfect-pixel-settings.jpg

**Comment by Sha1fei** [comment]
Добавить маркер на google maps, calendar, кнопки ripple effect, discrete slider.

**Comment by Sergio-Ka** [comment]
Переложил макеты и скрин настроек в папку maket в корне. На гуглокарту добавил маркер, календарь теперь по клику на кнопку возвращается на текущий день, риппл-эффект теперь работает по всему полю кнопки и начинается в том месте где курсор, а не по середине, дискретность слайдера добавил стандартными методами установив step = 25. Риппл-эффект был исправлен в рамках #3 issue

**Comment by Sergio-Ka** [comment]
Можно закрывать наверное, если все устраивает?

**Comment by chmnkh** [comment]
закрывай
