### ISSUE TITLE
Расставить пробелы в тернарниках

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/FlatUI#10]
Уже начал часто натыкаться, оставлю отдельное ишью
`(percent>=1000)?percent = "err.":percent = percent;` расставляй пробелы `(percent>=1000) ? percent = "err." : percent = percent;` плиз: читать это, когда это все слитно - тяжко.

**Comment by Sergio-Ka** [comment]
решил в рамках issue #8
