### ISSUE TITLE
Использовать темплейт строки, вместо конкатенации

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/FlatUI#11]
`a+" "+b` => ``` `${a} ${b}` ```

**Comment by Sergio-Ka** [comment]
Ну, это было единственное место, которое я пропустил. В остальном все нормально. Этот вопрос был иcправлен в рамках issue #13

**Comment by chmnkh** [comment]
в arrow-button тоже

**Comment by Sergio-Ka** [comment]
Еле нашел, старость видно подкрадывается. Просмотрел еще раз все, на этот раз вроде все.
