### ISSUE TITLE
Переусложенный код

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/FlatUI#13]
```
-(percent<10 && percent>=0)?xcoordtext = "38%":xcoordtext = "25%";
-(percent>99)?xcoordtext = "12%":xcoordtext = "25%";
```

Задача центрирования текста обычно сильно легче решается, чем ручное высчитывание каких-то там координат. Раз уж у тебя svg, посмотри в [эту](https://developer.mozilla.org/ru/docs/Web/SVG/Attribute/text-anchor) сторону, например.

**Comment by chmnkh** [comment]
```
-(percent>=1000)?percent = "err.":percent = percent;
```
1) такие тернарники обычно пишут так:
```
percent = percent >= 1000 ? 'err' : percent;
```
меньше буков, как видишь :)

2) вообще логика не совсем правильная. Лучше стараться никакие значения не переприсваивать, это усложняет код. percent - это входящее значение, оно по смыслу у тебя один раз пришло и все, если ты что-то там переприсваиваешь то по факту, у тебя уже смыл этой переменной меняется: раньше это был процент, а сейчас еще и текст с ошибкой? Логичней будет либо новую сущность ввести, типа displayedValue, либо прямо на месте использования решать что делать, т.е. вот так:
```
text.percentage__text(x= xcoordtext, y="66%")= percent >= 1000 ? 'err.' : percent
```

**Comment by Sergio-Ka** [comment]
Доделал. Согласен, стало лучше.

**Comment by chmnkh** [comment]
![image](https://user-images.githubusercontent.com/18498637/51455985-8a9adb00-1d7e-11e9-8be1-479ef937c3fb.png)
а так?)
в остальном норм, закрыть сам можешь как это поправишь

**Comment by Sergio-Ka** [comment]
Как бы дизайн и не предполагает отображение дробной части (на сколько можно судить по макету), а проценты они по хорошему до 100, а дальше смысл теряется, так как круг будет продолжать рисоваться уже одним и тем же цветом. Ввиду всего этого чуть изменил условие вывода сообщения об ошибке.
