### ISSUE TITLE
Некорректное использование тегов

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/FlatUI#16]
```
h2.events__day= day
h2.events__month= month
h2.events__title= title
```
h2 на title - я еще могу поверить, а на другое - нет)
поизучай этот вопрос получше

**Comment by Sergio-Ka** [comment]
Исправил.

**Comment by chmnkh** [comment]
`form.events__content`
что это за форма, без одного инпута? такая форма смысла не имеет, у тебя на сабмите просто ничего не полетит

`textarea.chat__input= inputPlaceholder` здесь нужно задать `name` обязательно, иначе так же сабмититься не будет; в simple-form тоже кое-где нету name'ов

`form.datepicker.js-datepicker` 
`form.form-elements__toggles-tick-boxes`
`form.search-drop-down__selectmenu-form`
`form.standard-buttons__container`
почему это формы - тоже не понятно. Не надо все блоки с инпутами обрамлять в формы, это же просто демонстрационный макет, ничего страшного, что у тебя инпуты вне форм находятся. Вот в задании с кастомными страницами если у тебя такое будет происходить - то это уже будет странно. Формы нужны, когда данные на сервер отправляются, а не для того, чтобы просто обрамить инпуты какие-то.

**Comment by Sergio-Ka** [comment]
Исправил.
