### ISSUE TITLE
Selectmenu ломается

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/FlatUI#18]
1. Открываешь дропдаун
2. Меняешь ширину экрана (тычешь ф12, например)
3. Видишь вот что:
![image](https://user-images.githubusercontent.com/18498637/51833622-89435280-232a-11e9-8b97-89df14191862.png)

Choose an option в качестве опции тоже не должен быть кстати, это же просто плейсхолдер.

**Comment by Sergio-Ka** [comment]
А это точно я должен править в рамках этого учебного задания? Там как я вижу проблема в том, что само выпадающее меню висит в div-блоке, который абсолютно позиционируется на странице, и координаты его добавляются в инлайновых стилях с помощью js, как и css-класс, который добавляет ему видимости. Все это происходит по клику. Соответственно координаты не обновляются при дальнейшем изменении размера, так как по логике предполагается, что если меню открыто, то дальше должен следовать выбор пункта меню, а не изменение размера страницы. Мне так кажется. То есть это все функционал библиотеки JQueryUI, а не мой кривой код. Я посмотрел немного документацию на этот виджет и код его и не вижу там функционала для исправления этого штатными методами. Может я чего-то не понимаю?

**Comment by chmnkh** [comment]
Над этим подумаю дополнительно, и отпишу.
Пусть пока висит.

**Comment by chmnkh** [comment]
на это забиваем, закрываю
