### ISSUE TITLE
Не стесняться использовать анонимные стрелочные функции

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/FlatUI#20]
```
$('.js-slider-discrete').each(function callback(index, domElement){
  new SliderDescrete($(domElement));
});
```
куча мест, где ты зачем-то используешь именованные как "callback" функции, в то время как лучше написать стрелочную функцию, потому что:
а) `(x) => {}` тупо лаконичнее и более легковесно, нежели `function(x) => {}` (меньше на целое слово!)
б) зачем делать эту функцию еще и именованной (тем более таким, по существу, бесполезным именем как "callback") вообще не совсем понятно :)

**Comment by Sergio-Ka** [comment]
Да там в стандартах было об именовании обработчиков, вот видно и вышла легкая каша в голове. Исправил. Тут же исправил issue #19
