### ISSUE TITLE
Не переопределять стили глобально

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/FlatUI#21]
```
.slider-with-pop-up

  &__handle_theme_orange
  &__range-min_theme_orange
    background #E75735 !important

.slider-value
  position absolute
  left -0.5rem
```
если slider-value - это класс, который либа накладывает, то не надо его глобально переопределять, а лучше сделать это через вложенный селектор, если конечно нету возможности руками свой класс задать.

**Comment by Sergio-Ka** [comment]
Нет, этот элемент я сам прикрепляю к слайдеру (к самому ползунку) в настройках слайдера в параметре create (то есть при инициализации), он не библиотечный. Соответственно стилей у него нет никаких, а стало быть я их не переопределяю, а просто определяю.
create: (event) => {
        const $sliderHandle = $(event.target).find('.ui-slider-handle');
        $sliderHandle.append(`<input class="slider-value js-slider-value" value="${value}"/><div class="slider-value__tail"></div>`);
      }

**Comment by chmnkh** [comment]
![image](https://user-images.githubusercontent.com/18498637/52925721-2b23f100-3365-11e9-90e7-70895ed8e0ef.png)
у тебя элемент slider-value__tail вне блока находится, во-первых
во-вторых, а почему это не сделать элементом slider-with-pop-up? почему отдельный блок?

**Comment by Sergio-Ka** [comment]
Исправил.
