### ISSUE TITLE
Пройтись по замечаниям из первого макета

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/FlatUI#4]
Тут примерно все те же проблемы, что были в первом макете (это классика). Так что можешь открывать ишью к 1 проекту и править здесь. Если исправить все нормально - вопросов к юикиту по идее практически не останется. Как только посчитаешь, что все ок - в этом ишью можешь отписаться.

**Comment by Sergio-Ka** [comment]
Всё сделал.
