### ISSUE TITLE
Не билдится проект

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/FlatUI#5]
index.styl зайди где шрифты импортятся
имена файлов и имена в коде не совпадают и проект не билдится

также jquery в зависимостях нету, и он не устанавливается со всеми пакетами с npm i, приходится руками доустанавливать
![image](https://user-images.githubusercontent.com/18498637/51296845-6bcfd800-1a50-11e9-9639-9f4801fa7a0a.png)

**Comment by Sergio-Ka** [comment]
Проблем со шрифтами в упор не вижу ни при сборке ни в консоли браузера, все собирается нормально. Проблема действительно была с jquery и как оказалось с UglifyJS-минификатором, который не понимает ES6, я его на babel minify поменял. Все это теперь работает нормально.

**Comment by chmnkh** [comment]
https://github.com/Sergio-Ka/FlatUI/tree/refactor/source/fonts

https://github.com/Sergio-Ka/FlatUI/blob/refactor/source/index.styl

Обрати внимание, как у тебя прописаны имена файлов в стилях (все с маленькой буквы), и как файлы со шрифтами называются (с большой буквы). Возможно у тебя регистр не учитывается в билде или типа того.

![image](https://user-images.githubusercontent.com/18498637/51455859-17916480-1d7e-11e9-90e6-49827bc1bed1.png)

**Comment by Sergio-Ka** [comment]
У меня ошибка не воспроизводится, так как у меня файлы шрифтов уже давно именованы в стиле lower-case-hyphenated в соответствии со стандартами, а здесь они почему-то лежат с большой буквы, и git разницы между ними не видит. Странно как-то это всё. Сейчас чего-нибудь придумаю.

**Comment by Sergio-Ka** [comment]
Перегрузил шрифты, теперь должно быть нормально. Только надо заново проект скачать.
