### ISSUE TITLE
Блоки не должны знать о контексте своего использования

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/FlatUI#7]
стандарт кнопка
```
  &_theme

    &_events
      display block
      background #FFFFFF
      color #4EB7A8
      font-size 0.6rem
      letter-spacing 0.03rem
      min-width 7.111rem
      min-height 1.444rem
      margin 1.056rem 0.5rem 1.333rem

    &_chat
      display block
      font-family 'Lato', Sans-Serif
      width 13.556rem
      height 1.944rem
```

Блок ничего не должен знать о том, где и как его используют. У тебя так это сделано, что ты для каждого юзкейса просто стили блока расширяешь. В итоге по мере разрастания проекта и разрастания частоты использования блока, у тебя размер стилей будет как снежный ком расти, это ад.

**Comment by Sergio-Ka** [comment]
Исправил.
