### ISSUE TITLE
Переписать опциональное навешивание модификаторов

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/FlatUI#8]
```
    -(color == "red")?cssClass = "standard-button_color_red ":cssClass = "standard-button_color_green ";
    -if (activeStatus == "inactive" && color == "red")
        -cssClass = "standard-button_inactive-red "
    -else if (activeStatus == "inactive" && color == "green")
        -cssClass = "standard-button_inactive-green ";
    -(size == "small")?cssClass += "standard-button_size_small ":cssClass += " ";
    -(effect == "ripple")?cssClass += "standard-button_ripple-effect ":cssClass += " ";
    -cssClass += `standard-button_theme_${theme}`;
```
это плохо читается (особенно тернарники без пробелов - никогда так не пиши)
```
    - const cssClass = 'standard-button'.concat(
    -   ` standard-button_color_${color}`,
    -   effect === 'ripple' ? ` standard-button_ripple-effect` : '',
    -   ...
    - );
```
если в таком духе написать, будет читаться сильно лучше: ты по сути тупо перечислишь какие модификаторы нужно навешать, притом на каждой строчке они будут четко видны

**Comment by Sergio-Ka** [comment]
Все вроде бы. Так же сразу в рамках этого решил issue #10.

**Comment by chmnkh** [comment]
```
    - activeStatus === "inactive" ? "" : ` standard-button_color_${color}`, 
    - activeStatus === "inactive" ? ` standard-button_inactive-${color}` : "", 
```
2 раза условие написано, это ж избыточно

Вообще странный подход. По идее модификатор с цветом должен всегда на кнопке быть: она же у тебя не теряет цвет, становлясь задизейбленой. А `inactive` - это булевый модификатор. 
Вариант 
```
&_inactive&_color
  &_green
  ...
  &_red
```
сильно логичнее выглядит здесь, как по мне

**Comment by Sergio-Ka** [comment]
Оно бы может и так, но inactive он разный для красного и зеленого, одно дело если бы там просто background-color становилось бы белым, но там ведь еще и шрифт цвет меняет в соответствии с цветом кнопки, а стало быть должен быть inactive-green и inactive-red. Маленько переделал, сейчас модификатор цвета висит всегда, а добавляемый модификатор активности переопределяет цвет заливки и цвет шрифта. На счет того, что дважды написал - исправил.
