### ISSUE TITLE
Избегать дублирования кода 

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/FlatUI#9]
`percentages-pie-chart.styl`

Вот этот вот запрос 1000 раз написан: 
```
@media only screen and (max-width 33.556rem)
  margin 1.111rem
```
хотя можно написать всего один.

Другой вопрос, что тебе придется `&:nth-child(n)` юзать скорее всего, чтобы специфичность победить. Но здесь на самом деле можно было не давать каждому элементу свой маргин чтобы пиксель перфект сделать, а на одном расстоянии их все уложить, было бы не пиксель в пиксель, но это норм, ибо макеты кривые. Тогда бы можно было просто на __graphics этот медиа запрос повешать, но в текущей ситуации только так. Это лучше, чем !important написать или дублировать этот запрос 1000 раз.

FYI: медиа запросы обычно в пикселях писать удобнее, потому что тебе надо же под какой-то размер экрана подстроиться, смысл там какие-то ремы фигачить (хотя может у тебя было какое-то обоснование?)? Тут можешь не перепиливать, просто на будущее.

**Comment by Sergio-Ka** [comment]
Сделал равные промежутки между кругами, с перфект пикселем не совпадает, но стало короче в стилях. На счет почему медиа-запросы в ремах - сказали же все размеры делать в ремах, я и сделал, изначально были в пикселях. Никакого обоснования, кроме этого. На будущее учту.
